### ISSUE TITLE
Problems with the launch. How to start? 

### ISSUE THREAD

**Issue by crypset** [watanabexia/Iwara-Telegram-Bot#1]
Hi.
There are problems with launching the bot.
After installing everything. I can't figure out which command to use. 

tried 
python main.py e dlsub
and other variations like a "python main.py"

P.s. I have python installed and all other things.

**Comment by xiatg** [comment]
I think it should be `python main.py -e dlsub`

**Comment by crypset** [comment]
> I think it should be `python main.py -e dlsub`

Yep, I tried this 
but getting a following error 

  File "D:\Soft\Iwara-Telegram-Bot\main.py", line 6, in <module>
    from dateutil.relativedelta import relativedelta
ModuleNotFoundError: No module named 'dateutil'

**Comment by xiatg** [comment]
It means the module called `dateutil` is missing. Try `python -m pip install python-dateutil`

**Comment by crypset** [comment]
> It means the module called `dateutil` is missing. Try `python -m pip install python-dateutil`

Thank you, that solved the problem. I tried just pip install dateutil. 
I found i more issue, Is better to set in config.json http://localhost:8081/bot. 0.0.0.0:8081 do not work for me. Mb someone will have this error too.
